name: CD

concurrency:  # Use this to prevent multiple CD workflows running at the same time
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:  # Use this to run workflow manually
    inputs:
      version:
        description: 'Version to deploy'
        type: string
        default: ''

  workflow_call:  # Necessery only if you want to use CD workflow in CI/CD workflow, otherwise you can remove this block
    inputs:
      version:
        description: 'Version to deploy'
        type: string
        default: ''

  push:  # Use this to run workflow on push
    branches: [ $default-branch ]

jobs:
  cd:
    uses: cdqag/workflow-deploy/.github/workflows/cd.yaml@v1
    secrets: inherit
    with:
      
      version: ${{ inputs.version }}
